monsters:
  - 'ゴブリン'
  - 'スライム'
  - 'ガーゴイル'
  - 'リザードマン'
  - 'オーク'

players:
  - 'あ'
  - 'う'
  - 'ケイ'
  - 'あみ'
  - 'サスケ'
  - 'かなみ'

males:
  - 'ユウ'
  - 'レオン'
  - 'ラスク'
  - 'サンダース'

females:
  - 'ルキア'
  - 'クララ'
  - 'サツキ'
  - 'アメリア'
  - 'シャロン'

