monsters:
  - 'カ'
  - 'ヒ'
  - 'ジン'
  - 'ロキ'
  - 'オーク'
  - 'サタン'
  - 'トロル'
  - 'ゴブリン'
  - 'スライム'
  - 'ベエマス'
  - 'ガーゴイル'
  - 'ケルベロス'
  - 'コカトリス'
  - 'フェンリル'
  - 'ワーウルフ'
  - 'バーサーカー'
  - 'スレイプニル'
  - 'リザードマン'
  - 'ヘカトンケイル'
  - 'ヤマタノオロチ'
  - 'ヨルムンガンド'
  - 'グラシャラボラス'
  - 'ケツァルコアトル'
  - 'ライカンスロープ'
  - 'ファイヤードラゴン'
  - 'ウィルオーウィスプ'
  - 'ジャックオーランタン'
  - 'モンゴリアンデスワーム'

players:
  - 'あ'
  - 'う'
  - 'ケイ'
  - 'あみ'
  - 'ぴぴ'
  - 'サスケ'
  - 'かなみ'
  - 'ハカセ'
  - 'すえぞう'
  - 'たろすけ'
  - 'ほむほむ'
  - 'ぬけさく'
  - 'ぐでちゃん'
  - 'こめたろう'
  - 'ゆとり代表'
  - 'うらしま太郎'
  - 'じゅうしまつ'
  - 'ホープダイヤ'
  - '魔術師マジック'
  - '巨人ジャイアント'
  - 'ストロマトライト'

males:
  - 'ス'
  - 'ヤン'
  - 'ユウ'
  - 'ラスク'
  - 'リック'
  - 'レオン'
  - 'グスタフ'
  - 'ゲオルグ'
  - 'ガウェイン'
  - 'サンダース'
  - 'トリスタン'
  - 'ヴィルヘルム'
  - 'サーディック'
  - 'クリストファー'
  - 'マクシミリアン'
  - 'フェルディナント'

females:
  - 'ミ'
  - 'アン'
  - 'サヤ'
  - 'ベル'
  - 'ルキア'
  - 'クララ'
  - 'サツキ'
  - 'アメリア'
  - 'シャロン'
  - 'アイリーン'
  - 'ナターシャ'
  - 'ミーティア'
  - 'ロザリンド'
  - 'コンスタンス'
  - 'ベアトリクス'
  - 'ジョゼフィーヌ'

